import { CardProps } from './Card';

export const subscriptionCardData: CardProps[] = [
  {
    color: 'bg-[#cfa9ed]',
    badgeText: 'Most Popular',
    title: 'Part-time Pro',
    description: [
      'One part-time creative dedicated to',
      'your continuous stream of projects.',
    ],
    price: '10200',
    billing: 'month',
    billingText: 'For ongoing tasks.',
    subscribeLink:
      'https://x55sj0z6ud1.typeform.com/to/t2vE6xtj#int=6oE6ozeq51Cxfcc8wC',
    infoText: 'Need more info? Let’s chat.',
    infoLink: 'https://calendly.com/betteroffstudio/30min?month=2024-06',
    features: [
      'Dedicated creative, 20 hrs weekly',
      'Two ongoing tasks',
      'Multiple revisions',
      'Access to 2 services',
      'Lightning turnarounds',
      'Pause or cancel anytime',
    ],
  },
  {
    color: 'bg-[#e0f07d]',
    badgeText: 'Best Value',
    title: 'Full-time Premium',
    description: [
      'One elite full-timer working',
      'simultaneously on multiple projects.',
    ],
    price: '15200',
    billing: 'month',
    billingText: 'Your augmented team.',
    subscribeLink:
      'https://x55sj0z6ud1.typeform.com/to/t2vE6xtj#int=28o7sDa9P3KF8NO4gl',
    infoText: 'Still not sure? Let’s discuss.',
    infoLink: 'https://calendly.com/betteroffstudio/30min?month=2024-06',
    features: [
      'Senior creative, 40 hrs a week',
      'Up to 4 ongoing tasks',
      'Multiple revisions',
      'Access to 3 services',
      'For robust workloads',
      'Pause or cancel anytime',
    ],
  },
];

export const projectCardData: CardProps[] = [
  {
    color: 'bg-[#cfa9ed]',
    badgeText: 'Client Pick',
    title: 'Brand Identity',
    description: [
      'Complete brand build from kickoff to',
      'delivery in 6 weeks.',
    ],
    price: '32500',
    billing: 'flat fee',
    billingText: 'Timeline: 6 weeks',
    subscribeText: 'Start Project',
    subscribeLink: '/',
    infoText: 'Need more info? Let’s chat.',
    infoLink: '#',
    features: [
      'Brand Strategy',
      'Concept Development',
      'Visual Direction',
      'Brand Messaging',
      'Website/Socials Direction',
      'Brand Guidelines',
    ],
  },
  {
    color: 'bg-[#e0f07d]',
    badgeText: 'Award Winner',
    title: 'Integrated Campaign',
    description: [
      'Translate business objectives into',
      'results across all touch points.',
    ],
    price: '18600',
    billing: 'flat fee',
    billingText: 'Timeline: 4–6 weeks',
    subscribeText: 'Start Project',
    subscribeLink: '/',
    infoText: 'Need more info? Let’s chat.',
    infoLink: '#',
    features: [
      'Messaging Strategy',
      'Multichannel Media Strategy',
      'Multiple Concept Directions',
      'Web/Social/Collateral Design',
      'Final Files Designed to Specs',
      'Content Launch Plan',
    ],
  },
  {
    color: 'bg-[#cfa9ed]',
    badgeText: 'Hot Seller',
    title: 'Website Update',
    description: [
      'Maximize leads and engagement with a',
      'design and functionality refresh.',
    ],
    price: '42500',
    billing: 'flat fee',
    billingText: 'Timeline: 12 weeks',
    subscribeText: 'Start Project',
    subscribeLink: '/',
    infoText: 'Need more info? Let’s chat.',
    infoLink: '#',
    features: [
      'Optimization audit',
      'Information Architecture',
      'UI/UX Design',
      'Full stack development',
      'SEO diagnostics',
      'Testing and launch',
    ],
  },
  {
    color: 'bg-[#e0f07d]',
    badgeText: 'Best-in-Class',
    title: 'Custom Website',
    description: [
      'End-to-end design and technology that',
      'best reflects your brand and vision.',
    ],
    price: '64000',
    billing: 'flat fee',
    billingText: 'Timeline: 16 weeks',
    subscribeText: 'Start Project',
    subscribeLink: '/',
    infoText: 'Need more info? Let’s chat.',
    infoLink: '#',
    features: [
      'Digital strategy',
      'Concept development',
      'IA, Sitemap, UI/UX Design',
      'Full Stack Development',
      'E-commerce Integration',
      'Testing and launch',
    ],
  },
  {
    color: 'bg-[#cfa9ed]',
    badgeText: 'Flexibility',
    title: '40-hrs Essentials Bucket',
    description: [
      'Hourly coverage for crucial',
      'maintenance tasks, broken into a bite-',
      'sized bundle.',
    ],
    price: '4000',
    billing: 'month',
    billingText: '$100 per/hr',
    subscribeText: 'Unlock Coverage',
    subscribeLink: '/',
    infoText: 'Need more info? Let’s chat.',
    infoLink: '#',
    features: [
      'Site maintenance',
      'SEO optimization',
      'Content updates',
      'Repricing',
      'Collateral design',
      'Marketing support',
    ],
  },
  {
    color: 'bg-[#e0f07d]',
    badgeText: 'Bandwidth',
    title: '60-hrs Intensive Bucket',
    description: [
      'Hourly coverage for multiple complex',
      'tasks ortwo priority initiatives per',
      'month.',
    ],
    price: '5400',
    billing: 'month',
    billingText: '$90 per/hr',
    subscribeText: 'Unlock Coverage',
    subscribeLink: '/',
    infoText: 'Still not sure? Let’s discuss.',
    infoLink: '#',
    features: [
      'Post blog articles',
      'Update site copy',
      'Expand products',
      'Event promo design',
      'Website maintenance',
      'Quick-turn projects',
    ],
  },
];
